### ISSUE TITLE
Viooz not working?

### ISSUE THREAD

**Issue by BooleanKing** [pixeltailgames/cinema#105]
Hey, whenever I try to use a Viooz video it just shows the website on the screen instead of playing the video. Any fixes or workarounds?

**Comment by WinterPhoenix96** [comment]
Sam dropped support for Viooz about 6 months ago. Neither him nor anybody else that contributes to the development of Cinema wanted to support it any longer, as it was breaking so often (with so many hacky fixes to keep it working), so support for it effectively stopped.

Terribly sorry for the inconvenience.
