### ISSUE TITLE
Cannot use "Say" Command on Dedicated Server - Lua Error

### ISSUE THREAD

**Issue by Hazbelll** [pixeltailgames/cinema#109]
When attempting to use the `say` command through Console on a Dedicated Server, it will fail on submission (and not be shown to any players - only echo back in Console) as Cinema is trying to check which theater they're in to filter the message out to others. Of course, Console is not a Player, so returns nil.

```
say Hello

[Cinema] gamemodes/cinema/gamemode/player.lua:188: attempt to call method 'GetTh
eater' (a nil value)
  1. unknown - gamemodes/cinema/gamemode/player.lua:188

Console: Hello
```

I am using the Workshop version of Cinema.

**Comment by samuelmaddock** [comment]
814db187af3b10737a7428100ac7c3c95a58bf6a
