### ISSUE TITLE
Video and any other streams playing too fast.

### ISSUE THREAD

**Issue by rst4d** [pixeltailgames/cinema#110]
Video is played faster than normal twice. This affects sounds too. 

I'm using Ubuntu 15.10 x64 with adobeflash x32 enabled in firefox plugins folder.

**Comment by rst4d** [comment]
Edit: i tested now, videos from vimeo playing normally without glitches.

**Comment by WinterPhoenix96** [comment]
I'm fairly certain that's going to be an issue caused by the fact you're running on Ubuntu. Unfortunately, GMod isn't exactly stable on Linux OSs, and frankly it's surprising you even got Flash Player to work in it. So...I don't know what to tell you. ^^;

**Comment by rst4d** [comment]
Let's see. I'm gonna try clear ubuntu 14.04 installation and after will write about it here.

**Comment by rst4d** [comment]
Surprised so much, this is working ok on clear installation. I will share solution to fix this later.

**Comment by WinterPhoenix96** [comment]
Huh. Alright then.

**Comment by rst4d** [comment]
The issue was with audioserver which working bad with external audio card . Thank you for putting me on the right path, i completely fixed this now.
