### ISSUE TITLE
bad argument #1 to 'match'

### ISSUE THREAD

**Issue by MrCraigTunstall** [pixeltailgames/cinema#111]
gamemodes/cinema/gamemode/modules/theater/services/sh_blip.lua:7: bad argument #1 to 'match' (string expected, got nil)

**Comment by WinterPhoenix96** [comment]
This is what happens if somebody enters in a blank url for a video request, most likely through using the `cinema_video_request` command. It does not, however, affect much of anything.

**Comment by samuelmaddock** [comment]
cd19880c8ae3bc653a215ec02f6600fdd29d2bc4
