### ISSUE TITLE
Addon-breaking CleanUpMap

### ISSUE THREAD

**Issue by wyozi** [pixeltailgames/cinema#117]
[This](https://github.com/pixeltailgames/cinema/blob/master/cinema/gamemode/modules/theater/sv_init.lua#L15) line of code seems to be causing quite a lot trouble in addons that have their InitPostEntity registered before Cinema's and spawn entities in it (which I believe is quite widely used hook for spawning entities).

I'd assume cleaning up the map is there for development, but if I understood the context correctly only the cinema entities should need removing. In any case I believe the cleanup should at least only happen if a development cvar is set.

**Comment by samuelmaddock** [comment]
a77de4972b875643a6207bc7a75c8f094b244354
