### ISSUE TITLE
Invalid Request video youtube

### ISSUE THREAD

**Issue by RubenJast** [pixeltailgames/cinema#123]
Pls My Select The Video and Invalid Request

**Comment by WinterPhoenix96** [comment]
You're going to have to be more specific. What is the video's link and on what service does it reside?

**Comment by RubenJast** [comment]
The Addon Cinema  my select the video and my click Request URL and invalid request

**Comment by WinterPhoenix96** [comment]
What video?

**Comment by FarukGamer** [comment]
We cannot help you don't describe the issue a bit clearly.

Do you have a legal copy of Garry's Mod?
Did you tried updating the Gamemode?
Where you've tried Singleplayer or Multiplayer ?

**Comment by YoshiCrystal** [comment]
I have the same problem.When i go to search a video on youtube and i click GET LINK the game says :
Procesando YouTube solicitud...
invalid request

**Comment by FarukGamer** [comment]
Can you send me the YouTube link please

**Comment by YoshiCrystal** [comment]
https://www.youtube.com/watch?v=eVTXPUF4Oz4

**Comment by FarukGamer** [comment]
What video you tried?

**Comment by FarukGamer** [comment]
The video is working completely fine, their is probably a issue on you side. Have you tired with a Different video?

**Comment by YoshiCrystal** [comment]
ok
