### ISSUE TITLE
VIP and Admin Only areas

### ISSUE THREAD

**Issue by ThatCrazyGuy** [pixeltailgames/cinema#124]
Hi,

I noticed the VIP Implementation code in the cinema gamemode and I was wondering how I would go about setting it up so that certain ULX ranks can access certain theaters, but others can't. I tried an elseif statement using the code provided, but that blocked any ranks from entering the privileged rooms.

Thanks.

Crazy

**Comment by samuelmaddock** [comment]
https://github.com/pixeltailgames/cinema/blob/master/cinema/gamemode/modules/theater/sv_hooks.lua#L70-L96
