### ISSUE TITLE
Changing characters... ever?

### ISSUE THREAD

**Issue by AdAstron** [pixeltailgames/cinema#128]
Hello. As it usually goes in most garrys mod game modes, one holds "C" to bring up the character change menu... I read on the FAQ that the lua must be edited in this game mode for ANY user interaction of that kind.

I'm running a small private server with my friends, and we'd just like to be able to change characters. No spawning things, no fancy enhancements.

Could someone please direct me to the lua adjustments I must make to the original file? There are so many popular cinema maps that somehow have items/characters changers...

**Comment by WinterPhoenix96** [comment]
If you want to do it the easy way:
Simply go to Sandbox mode, change your player model to one that you like that's included with GMod, and rejoin the server.

If you want to do it the medium difficulty way:
Install PointShop or PointShop 2 on your server and then use that to change player models.

If you want to do it the hard way:
You're going to have to know Lua and code it yourself. See [GM:PlayerSetModel](http://wiki.garrysmod.com/page/GM/PlayerSetModel) and [PLAYER:SetModel](http://wiki.garrysmod.com/page/PLAYER/SetModel).

Adding custom models though, will require more effort. See [Workshop for Dedicated Servers](http://wiki.garrysmod.com/page/Workshop_for_Dedicated_Servers) for the easiest method of doing that.

**Comment by samuelmaddock** [comment]
Closing since this isn't an issue. However, following what @WinterPhoenix96 said should point you in the right direction.

The `cl_playermodel <player-model-id>` console command is another alternative for changing player models while in a game.

**Comment by AdAstron** [comment]
Thank you all so much for the help!
