### ISSUE TITLE
Ads showing at the start of videos

### ISSUE THREAD

**Issue by JesseUK** [pixeltailgames/cinema#130]
Hi,

I don't know why but from today ads at the start of videos have started showing and they last for up to 2 mins... no one is able to skip the ad and it's kinda annoying :(

**Comment by samuelmaddock** [comment]
YouTube?

**Comment by JesseUK** [comment]
Yeah

**Comment by JesseUK** [comment]
http://images.akamai.steamusercontent.com/ugc/436110443018591128/86D6CAE4FABADDBB10C1545B20DC029DFE35F714/

http://images.akamai.steamusercontent.com/ugc/436110443018590920/C492E79187ADE2D04535F80687F063FC72950D12/
