### ISSUE TITLE
Twitch changed API

### ISSUE THREAD

**Issue by FarukGamer** [pixeltailgames/cinema#133]
When visiting the Twitch via in-game browser, the page stays blank. This might be happend because of api changes by the Twitch devs...

This should give more details
https://www.reddit.com/r/Twitch/comments/5d6kvm/dev_action_required_twitch_api_version_update/

**Comment by WinterPhoenix96** [comment]
Twitch.tv no longer works in Cinema, and we don't have a realistic way to fix it due to Awesomium's limitations. Please see [https://github.com/Facepunch/garrysmod-requests/issues/791](this issue) for more information.
