### ISSUE TITLE
Reqest: Gmod Cinema: Google Drive Support (with proof that you absolutely can implement this kind of thing)

### ISSUE THREAD

**Issue by SkullBonez2** [pixeltailgames/cinema#134]
Ok, so I'd like to start with this, I know the community has been nagging about this feature, but I'm not trying to jump onto that train of 'Please, Please, Please, can you Please give us this?' because that is not my style.

Although I think this will never be admitted into the mod, I'd like to start with a discovery that I found out (not me, but basically a feature of Google Drive)

Firstly, like youtube, there IS a way to autoplay the movies/videos on Google Drive, Lets take this link for example: https://docs.google.com/file/d/0BzaKcPjzHMOOci1CZ2FTeThYSDQ/preview

This link is of the movie Wall-E

Now if you add the following to the end of the link: "?autoplay=1" (without quotation marks) the film automatically plays with the API of what is similar to youtube: 
![untitled](https://cloud.githubusercontent.com/assets/24311212/20825776/99c7262c-b8ba-11e6-928c-b73a637818b7.png)

Also, adding "?autoplay=1" (without quotation marks) like i said before, It really does autoplay, so this should make it possible for GMod cinema, right?

I'll see what you think about my discovery (not that I hope that it will be pleasant), also here is a link to all the movies in the universe, on Google Drive (this could be added to the cinema menu): https://www.reddit.com/r/fullmoviesongoogle/

Thank you :)

Please don't flag this just because it isn't an "issue"

**Comment by SkullBonez2** [comment]
I mean, this would make sense because the idea of this gamemode is the time where you were "sitting down on a lazy afternoon with your friends, drinking a cup of hot cocoa and **_watching a movie_**"

**Comment by SkullBonez2** [comment]
Also, I found a server which allows this type of video, so why cant that be in this game mode?

Go look at Cereal Box Cinema/Swamp Cinema, it allows all types of other sources of video including Google Drive, KissAnime and KissCartoon, What's not to love if they are in this mode? I hope the devs notice this, if a small group of chums who run a server can make it work, why can't the devs? People have to watch Markiplier/Poodiepie/Jacksepticeye in 99.999999% of servers, but only one server can decipher Google Drive and other .mp4 hosted sites, and it isn't even made by pixelTail games.

**Comment by SkullBonez2** [comment]
Now, What I think is that APIs like youtube can be controlled by jscript code:

Youtube has Jscript code to change when the video starts

Google Drive has Jscript code to change when the video starts AND autoplay

Mind-Blow!

Google drive support shouldn't be a problem. But i want answers as to why if it is a problem

**Comment by samuelmaddock** [comment]
There are two main components for Cinema services: metadata gathering (title, duration, etc.) and control of the clientside/browser video player. Your solution only accounts for the latter.

One reason I chose to make Cinema open source is to allow servers to differentiate themselves through the addition of new features. I currently don't have plans to continue updating Cinema, so I encourage servers to add their own services if they wish to attract more players. If they want to submit their changes back into this code repo, that's cool. If not, that's fine too.

The [Media Player addon](http://steamcommunity.com/sharedfiles/filedetails/?id=546392647) has some support for Google Drive, however, I'm unsure of its current working state.

**Comment by SkullBonez2** [comment]
That's funny 😂 
I find it funny that this mod supports Google Drive, and it uses the same Cinema-kind of overlay.

Why can't you just port this over into cinema? Both mods are made by you after all

**Comment by samuelmaddock** [comment]
I'm currently focused on other projects and I've since stopped developing for GMod. It's also probably not worth investing any more time into this project unless Facepunch/garrysmod-requests#791 is implemented.

**Comment by SkullBonez2** [comment]
I wouldn't give a crap if this is implemented without server side streaming, All I'm saying is to add this service as a Viooz replacement

**Comment by SkullBonez2** [comment]
Ok, sorry for harassing the GitHub. I understand this issue is because Garry can't give a shit about updating Awesomium.

**Comment by SkullBonez2** [comment]
Try to start up a trend: #GarryAwesomium

**Comment by jackson-c** [comment]
Note that on Swamp Cinema, although Google Drive used to work flawlessly, it no longer supports seeking due to awesomium issues, so if you walk into a theater mid-video it will start from the beginning on your screen.

**Comment by FarukGamer** [comment]
Instead of using the Flash Player, you could use the Silverlight Player?

https://github.com/Afterster/videojs-silverlight

**Comment by jackson-c** [comment]
Can it be made to play google drive videos? Right now our code uses this: http://stackoverflow.com/questions/17779197/google-drive-embed-no-iframe

**Comment by FarukGamer** [comment]
@jackson-c MediaElement.js supports YouTube by default, so it should also work with Google Drive.
http://mediaelementjs.com/examples/?name=youtube

**Comment by FarukGamer** [comment]
@jackson-c MediaElement.js It should be working, since it uses the YouTube Player APi
http://mediaelementjs.com/examples/?name=youtube

**Comment by FarukGamer** [comment]
@jackson-c Google Drive should be working on MediaElement.js, since it uses the YouTube Player API
http://mediaelementjs.com/examples/?name=youtube

**Comment by jackson-c** [comment]
I can't even get that example code to work off of their website.

Google Drive does not technically use the YouTube Player API. It uses a video.google.com player which has the same-looking interface and happens to be generally compatible with YouTube API calls, but this functionality is not officially supported and does not mean it must be compatible with third-party YouTube players out of the box.

IIRC - the video.google.com player still works in Awesomium (with flash), but no longer supports JS API calls due to a same-origin policy. I also just tried implementing drive as an IFRAME of the page in OP's post, using autoplay=1 and t=xxx URL parameters which would at least allow some form of seeking by refreshing the page, but unfortunately the IFRAME can't be created due to, again, a same-origin policy. It would, however, be possible to get seekable google drive to work using this and LUA code to directly control the panel's URL, but that's far outside the design of the Cinema gamemode and up to individual server owners to figure out (i'll probably do it next week)

**Comment by FarukGamer** [comment]
For bypassing Same-Origin-Policy (SOP) should be this maybe useful. https://www.sitepoint.com/working-around-origin-policy/
