### ISSUE TITLE
HTML5 players not working

### ISSUE THREAD

**Issue by travishughes2002** [pixeltailgames/cinema#149]
when me and others tried playing videos from youtube and soundcloud they both said they couldn't play the HTML5 player.

**Comment by CattoGamer** [comment]
Simple said, YouTube had recently a change..
I'll suggest you use the Chromium branch

Right click on Garry's Mod > Properties > Betas
Now use the Dropdown and click on chromium, Done.

**Comment by travishughes2002** [comment]
ok thanls

**Comment by WinterPhoenix** [comment]
More info here: https://github.com/Facepunch/garrysmod-requests/issues/531#issuecomment-422889172

**Comment by travishughes2002** [comment]
ohhhhhhh ok now i understand thanks
