### ISSUE TITLE
Doesn't detect Flash on Linux.

### ISSUE THREAD

**Issue by iirelu** [pixeltailgames/cinema#23]
Downloaded Flash from [this](http://get.adobe.com/flashplayer/otherversions/) page, Linux (64-bit) and Flash Player 11.2 for Ubuntu (apt). Everything else works (edit: seats are broken, some textures are missing) on the Linux version of Gmod, but flash doesn't get detected.

**Comment by ElectricPrism** [comment]
Issue is solved by the user manually symlinking `libflashplayer.so` into .../bin/plugins in the gmod folder:
https://github.com/pixeltailgames/cinema/issues/125
