### ISSUE TITLE
Suggestion: Video tables include full URL to its source

### ISSUE THREAD

**Issue by mitterdoo** [pixeltailgames/cinema#51]
I believe there should be an index in video tables that are in video requests that should be the URL to the video. The only part of the URL that is in the table is the data, which is the characters after the "/watch?v=" or the numbers after "vimeo.com/" This isn't very useful, and there should be a separate index of the table or just a function that returns the URL of its video.

**Comment by samuelmaddock** [comment]
If you still really need the URL, you should be able to construct it from the data and video type.
