### ISSUE TITLE
Local Video

### ISSUE THREAD

**Issue by PeterFour** [pixeltailgames/cinema#57]
Well maybe it's not the purpose of the mod to setup a local stream among the server.
But it can be great to stream our own file, or maybe add compatibility for something like VLC streaming system for instance

**Comment by secretplop** [comment]
I Know that this is old, but is this still possible? I have been trying to do this but cinema won't accept the url.
Sorry If Im just being stupid and / or annyoing.

**Comment by WinterPhoenix96** [comment]
It should, yes. However you also have to run `cinema_allow_url 1` in console in order for `cinema_video_request` to work with Webpage links.
