### ISSUE TITLE
Please add back video downvoting as an option...

### ISSUE THREAD

**Issue by swamponions** [pixeltailgames/cinema#62]
I am one of the developers of Cereal Box Cinema and we have been using an old version of the cinema gamemode simply because we want players to be able to downvote videos in the queue. This has been working okay, although it is a problem how we don't get access to the latest bugfixes and updates. Now, however, the sql format of client side video request logging has changed, and the outdated version of the cinema gamemode we run no longer works with clientside logging (the data and type fields are blank because the server doesn't send that data, but the client uses that data when searching the local database to overwrite videos). We are not very good lua coders, and fixing issues like these as they arise as our gamemode becomes dated is very hard for us. However, switching to the latest version of the gamemode and losing downvoting is not an option either because we think it's more fun when getting your video to play requires timing and skill. Considering that we are one of the largest gmod cinema servers, I think it is reasonable to request that video downvoting is added back as an option (like cinema_queue_mode) so that we can update our gamemode and not lose downvoting.

**Comment by samuelmaddock** [comment]
As @WinterPhoenix96 stated, downvoting was abused far too often to the point where all videos in a queue had negative vote values.
