### ISSUE TITLE
cinema_url cvar doesn't work

### ISSUE THREAD

**Issue by rbreslow** [pixeltailgames/cinema#72]
It says it's a replicated cvar on the server but it doesn't actually change on my client and I am still stuck with the default URL.

**Comment by neico** [comment]
simple trick, server.cfg:

cinema_url			"0"
cinema_url			"<your custom url>"

it's most likely an issue with convar's created in lua, not sure if anyone reported that yet.

**Comment by WinterPhoenix96** [comment]
That might be a good workaround...I wonder why it would cause those kinds of issues though.

[This is the code though, if you wanna take a look.](https://github.com/pixeltailgames/cinema/blob/a72276c1e21911b79d7ea4e73c8846be948abaa9/cinema/gamemode/modules/theater/sh_commands.lua#L1)

**Comment by neico** [comment]
As I said, most likely a issue with the way gmod creates lua based convar's with replication...

**Comment by WinterPhoenix96** [comment]
Yeah. Time for some investigative work.
