### ISSUE TITLE
Open VLC media streams [Enhancement]

### ISSUE THREAD

**Issue by Redbyte1** [pixeltailgames/cinema#76]
Do you think it would be possible to make it so we could open streams from VLC so the content that we could watch wouldn't be limited to just Youtube, Twitch, and the lot. So say you could have a home video that you don't want to upload because it has copyrighted music in the background but you would like to share it with your friends. You could stream it with VLC and tune it without needing to upload it

**Comment by samuelmaddock** [comment]
I would recommend using an RTMP server as mentioned in #57.
