### ISSUE TITLE
Cinema doesnt work at all. 

### ISSUE THREAD

**Issue by EaRthQaQe** [pixeltailgames/cinema#81]
There are no TVs and no Doors.
I already watched the FAQ!
I have reinstalled flashplyer
I have resubbed the cinema mod and the theatron
 But it doesnt work!

I started it by:
Start Game > Cinema > Map theatron > Single Player > Start

Can sbdy help me? :) thx

**Comment by samuelmaddock** [comment]
Since I'm currently unable to reproduce this problem, I'm going to assume that this is the result of conflicting addons. You should try disabling all of your active workshop addons and only enabling Cinema. Please report back if you're able to find a way to reproduce this issue.
