### ISSUE TITLE
Suggestion: Perhaps adding KissAnime as a video source?

### ISSUE THREAD

**Issue by Holooo** [pixeltailgames/cinema#83]
To whom it may concern,

It has come to my attention that the lack of anime on YouTube/Vimeo is quite disturbing.
Would it be possible to add http://kissanime.com as a video source?

Regards,
Holooo

**Comment by WinterPhoenix96** [comment]
KissAnime is [url=https://trello.com/c/VCFP84hy]being worked on[/url] for my server, YukiTheater (an Anime-Themed fork of Cinema), and we plan to release the service publicly for all of Cinema once we're done.

**Comment by Holooo** [comment]
Ahh thank you kind sir.

**Comment by WinterPhoenix96** [comment]
Sure thing~ You should see it in a week or two.

**Comment by Holooo** [comment]
Also, would 60fps be possible for YouTube videos that can support 60fps?

**Comment by WinterPhoenix96** [comment]
Debatable... AFAIK the player should automatically be playing at 60FPS with 1080p or 720p by default, but there's been some debate over whether or not this is actually happening.

**Comment by Holooo** [comment]
From my experience, the video does play at 1080/720p, but the FPS is around 30 like usual :/

**Comment by WinterPhoenix96** [comment]
Yeah exactly. And I don't really know of a way to tell if the video is playing at an actual 60FPS or not, for sure.

**Comment by Holooo** [comment]
Oh well, guess it can't be helped.

**Comment by SpadingAce** [comment]
Please make this a thing, we really, really need anime on the cinema gamemode.
I'm trying to get my friend into anime but just dropping him with an episode and waiting for him to finish is really dumb when I can just watch it with him and comment on events that happen.

+200 from me

**Comment by samuelmaddock** [comment]
At this time there are no plans to implement KissAnime into the official Cinema addon. However, YukiTheater does support it so you're welcome to join their server.

**Comment by WinterPhoenix96** [comment]
Please keep in mind it's not functional at the moment. [We are working on it however.](https://trello.com/c/VCFP84hy)
