### ISSUE TITLE
I can't click any of the UI!?

### ISSUE THREAD

**Issue by OldJigglypuff** [pixeltailgames/cinema#86]
I hold Q and obviously the menu shows up, but whenever I go to try click something nothing happens!?
e.g. it highlights the selected option im hovering over but nothing happens?

**Comment by samuelmaddock** [comment]
Are there any errors in the console? You might have a conflicting addon which is causing this. To test this, you should disable all other addons and only enable Cinema.

**Comment by OldJigglypuff** [comment]
Cinema is the only addon I have aswell as 1 cinema map to try and see if this would work in singleplayer.....The only error I see is the failed to change gamemode to cinema upon load up of gmod but then I just manually select cinema either way. Also not sure if this helps but when I hold tab aswell to show up the menu with the lobby list etc where it says click mouse to activate nothing happens, no mouse....nothing. (Im using a laptop, not that that would be causing something right???

**Comment by swamponions** [comment]
Actually it may be disabling your mouse input when it detects typing eg. when tab is being held.
