### ISSUE TITLE
Seats stop working when the player in them logs out.

### ISSUE THREAD

**Issue by swamponions** [pixeltailgames/cinema#87]
We've been struggling with this issue for ages on the Autism Box. I even saw a complaint about it on the yukitheater forums the other day when this guy told me he raided your forum and I went to see what he did. Surely there must be some way to fix this, perhaps by un-seating a player right before they disconnect?

Also, on an unrelated note, I made a Google Drive Video integration thing and you can put it on the master branch if you want. (It's not backdoored, honest!!!)

**Comment by samuelmaddock** [comment]
I'll take a look.

**Comment by WinterPhoenix96** [comment]
This one has been a heck of a problem for a while now. I still haven't managed to fix it myself, but hopefully you see something I'm not.

**Comment by samuelmaddock** [comment]
Fixed in 1a2f30b, I'll update the Workshop addon a little later.

**Comment by swamponions** [comment]
Thanks, Samuel.
