### ISSUE TITLE
Possible workaround for embed-disabled youtube videos

### ISSUE THREAD

**Issue by swamponions** [pixeltailgames/cinema#88]
Many videos which people try to play contain copyrighted music, and thanks to the fine lawyers who work for record labels, these videos can't be played on cinema. They just show as a black screen. What if, instead of loading the video from the API (video.google.com or whatever), it just loaded the actual youtube page itself and fullscreened the video?

This would have two benefits: embed-disabled videos would be playable, and views would actually get counted on the videos watched.

One problem I can see with this is the ads which play before youtube videos sometimes. Could they be blocked by executing javascript on the page or something?

**Comment by samuelmaddock** [comment]
The problem with this approach is that it isn't official supported by YouTube and will need to be maintained each time their interface changes. This is what happened with Viooz and is something I'd like to avoid.
