### ISSUE TITLE
Cannot request a video in my server

### ISSUE THREAD

**Issue by ScratchyLuny** [pixeltailgames/cinema#98]
hey everyone ... I hope you guys can help me out.

I want to play videos on my server but its dont working for me and another users. I removed the sd.db but still i get those errors 

AWESOMIUM: Initialized instance for video request window
Altering 'cinema_requests' table for updated structure...
AWESOMIUM: Destroyed instance for video request window

**Comment by samuelmaddock** [comment]
Could you describe the problems you're experiencing in the gamemode? Are you able to request videos and do the requests timeout? Also, are you hosting a dedicated or listen server?

**Comment by ScratchyLuny** [comment]
I host a Linux Listen Server well if i request IT wount play the Video always coming IT come a Problem whit requested Video. The gamemode is cinema so yea 
..... Sorry my english sucks i just wake up

**Comment by swamponions** [comment]
Did you remove sv.db on your server or the client? Are there any error messages in the server console when you play a video?

**Comment by ScratchyLuny** [comment]
On the server... No dont think so
